# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Portfolio
tagline:          'Darren Poon'
description:      'Passionate about coding and learning new tech. I hope I will be able to work with a team with similar passion.'
baseurl:          /
url:              https://dyhpoon.me
error:
pdf_url:		      https://github.com/dyhpoon/dyhpoon.github.io/raw/master/public/resume/darrenCV.pdf
email:            dyhpoon@gmail.com

author:
  name:           'Darren Poon'
  url:            https://dyhpoon.me

paginate:         1

# Custom vars
github:
  repo:           https://github.com/dyhpoon

linkedin:
  url:            https://www.linkedin.com/in/darren-poon-7b2447b9

plugins:
    - jekyll-paginate
