# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Portfolio
tagline:          'Darren Poon'
description:      'Passionate in coding and learning new tech. I hope I will be able to work with a team with similar passion.'
url:              http://dyhpoon.github.io/resume
baseurl:          /
error:
  redirect_url:   /resume
pdf_url:		  https://github.com/dyhpoon/dyhpoon.github.io/raw/master/public/resume/darrenCV.pdf
email:            dyhpoon@gmail.com

author:
  name:           'Darren Poon'
  url:            https://twitter.com/mdo

paginate:         1

# Custom vars
github:
  repo:           https://github.com/dyhpoon

linkedin:
  url:            https://hk.linkedin.com/pub/darren-poon/b9/447/7b2

docker:
  url:            https://hub.docker.com/u/dyhpoon/

gems:
    - jekyll-redirect-from